"""add like table

Revision ID: 068d8b202e6a
Revises: e8b5553f7c84
Create Date: 2022-11-26 16:21:31.744047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068d8b202e6a'
down_revision = 'e8b5553f7c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('all_like', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_like_post_all_like'), ['all_like'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key('comment_post_id_fkey', 'post', ['post_id'], ['id'])

    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_like_post_all_like'))

    op.drop_table('like_post')
    # ### end Alembic commands ###
