"""add like table

Revision ID: aad032cd52ab
Revises: 20a58f80e010
Create Date: 2022-11-26 18:29:15.715948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad032cd52ab'
down_revision = '20a58f80e010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.drop_constraint('like_post_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('like_post_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
