"""update table like

Revision ID: b33bf4aada49
Revises: d403c2080d34
Create Date: 2022-11-27 11:33:52.720307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33bf4aada49'
down_revision = 'd403c2080d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_like_post_all_like')
        batch_op.drop_column('all_like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_like', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_like_post_all_like', ['all_like'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
