"""update table like

Revision ID: d403c2080d34
Revises: aad032cd52ab
Create Date: 2022-11-27 11:27:46.744783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd403c2080d34'
down_revision = 'aad032cd52ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('like_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_like_post_like_date'), ['like_date'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_like_post_like_date'))
        batch_op.drop_column('like_date')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
